version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    hostname: es-host
    environment:
      - network.publish_host=es-host
      - discovery.zen.ping.unicast.hosts=tasks.elasticsearch
      - discovery.zen.minimum_master_nodes=2
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - LOGSPOUT=ignore
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1G
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports:
      - "5601:5601"
    environment:
      - xpack.security.enabled=false
      - LOGSPOUT=ignore
    depends_on:
      - elasticsearch
  logstash:
    image: sentara/logstash
    build:
      context: ./logstash
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - elasticsearch
  logspout:
    image: sentara/logspout
    build:
      context: ./logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ROUTE_URIS=logstash+tcp://logstash:5000 # Use TCP 
      - RETRY_STARTUP=1
    depends_on:
      - logstash
    deploy:
      mode: global
      
volumes:
    elasticsearch-data: