version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - LOGSPOUT=ignore
      - xpack.security.enabled=false
    restart: always
  logstash:
    build:
      context: ./logstash
    environment:
      - LOGSPOUT=ignore
    restart: always
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports:
      - "5601:5601"
    environment:
      - LOGSPOUT=ignore
    restart: always
    depends_on:
      - elasticsearch
  logspout:
    build:
      context: ./logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ROUTE_URIS=logstash+tcp://logstash:5000 # Use TCP 
      - RETRY_STARTUP=1
      - LOGSPOUT=ignore
    restart: always
    depends_on:
      - logstash
      
volumes:
    elasticsearch-data: