version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - node.name={{.Service.Name}}.{{.Task.Slot}}
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - discovery.zen.minimum_master_nodes=2
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - LOGSPOUT=ignore
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 180s
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 1G
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    ports:
      - "5601:5601"
    environment:
      - xpack.security.enabled=false
      - LOGSPOUT=ignore
    depends_on:
      - elasticsearch
  logstash:
    image: jdharmon/logstash:5.5.0
    build: ./logstash
    environment:
      - LOGSPOUT=ignore
    depends_on:
      - elasticsearch
  logspout:
    image: jdharmon/logspout
    build: ./logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ROUTE_URIS=logstash+tcp://logstash:5000 # Use TCP 
      - RETRY_STARTUP=1
      - DOCKER_LABELS=1
    depends_on:
      - logstash
    deploy:
      mode: global
  curator:
    image: jdharmon/curator
    build: ./curator
      
volumes:
    elasticsearch-data:
